<!DOCTYPE html>
<html>
<head>
    <title>Prescription</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 14px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .title {
            font-size: 22px;
            font-weight: bold;
            color: #4f46e5;
        }

        .section {
            margin-bottom: 15px;
        }

        .label {
            font-weight: bold;
        }

        .box {
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
        }

        .footer {
            margin-top: 30px;
            font-size: 12px;
            text-align: center;
            color: #777;
        }
    </style>
</head>
<body>

<div class="header">
    <div class="title">KASS Care</div>
    <div>Prescription</div>
</div>

<div class="section box">
    <p><span class="label">Patient:</span> {{ $order->client->name ?? 'N/A' }}</p>
    <p><span class="label">Medication:</span> {{ $order->medication_name }}</p>
    <p><span class="label">Dosage:</span> {{ $order->dosage ?? 'N/A' }}</p>
    <p><span class="label">Frequency:</span> {{ $order->frequency ?? 'N/A' }}</p>
    <p><span class="label">Quantity:</span> {{ $order->quantity ?? 'N/A' }}</p>
    <p><span class="label">Refills:</span> {{ $order->refills ?? 0 }}</p>
</div>

<div class="section box">
    <p><span class="label">Pharmacy:</span> {{ $order->pharmacy_name ?? 'N/A' }}</p>
    <p><span class="label">Phone:</span> {{ $order->pharmacy_phone ?? 'N/A' }}</p>
    <p><span class="label">Fax:</span> {{ $order->pharmacy_fax ?? 'N/A' }}</p>
</div>

<div class="section box">
    <p><span class="label">Instructions:</span></p>
    <p>{{ $order->instructions ?? 'No instructions provided.' }}</p>
</div>

<div class="section">
    <p><span class="label">Status:</span> {{ ucfirst($order->status) }}</p>
    <p><span class="label">Date:</span> {{ $order->prescribed_at }}</p>
</div>

<div class="footer">
    Generated by KASS Care SaaS
</div>

</body>
</html>
